### PR TITLE
Adding argtable command line parser library

### PR DESCRIPTION
**Pull request by Spacefreak18**

### CODE REVIEW

**Comment by emmett1** [comment]
Dont use 'PREFIX=$PKG/usr', use 'PREFIX=/usr' instead. DESTDIR already handled fakeroot location to $PKG.

**Comment by Spacefreak18** [comment]
Missed. And fixed.

**Comment by lumarogit** [comment]
Please, can you replace lines 12-16 with the command 'autoreconf -vfi' and try again?

Thanks.

**Comment by Spacefreak18** [comment]
fixed

**Pull request merged**
