### PR TITLE
Added jgmenu port simple X11 menu

### PR DESCRIPTION
**Pull request by SACViper**
jgmenu is intended for to used with openbox and tint2

### CODE REVIEW

**Comment by emmett1** [comment]
nice ports :D 
btw, i hope you can fix a few things first before i merge it:
1) remove empty array, so spkgbuild more clean
2) for github url use '$name-$version' for the source tarball, so the source downloaded will proper name, example for this case 'https://github.com/johanmalm/jgmenu/archive/v$version/$name-$version.tar.gz'

**Comment by emmett1** [comment]
thank you for that fix :)

**Comment by SACViper** [comment]
I didnt even got chance to reply to you properly that was fast :)

**Comment by emmett1** [comment]
its ok ;D

**Pull request merged**
