### PR TITLE
added intel-ucode and iucode-tool for intel ucode support if required

### PR DESCRIPTION
**Pull request by itsManjeet**

### CODE REVIEW

**Comment by itsManjeet** [comment]
Done fixes

**Comment by emmett1** [comment]
Looking good now. Except few stuff like `foo-{bar,baz}` which is unsupported for POSIX still there. Please run `pkgbuild -g` to generate `.checksums` file and run `pkgbuild -p` to generate `.pkgfiles` file, so i can examine it.

**Comment by itsManjeet** [comment]
fix the spkgbuild for POSIX stds and generated checksums and pkgfiles for both packages

**Comment by emmett1** [comment]
nice. thank you :D

**Pull request merged**
