### PR TITLE
Firefox 101 update

### PR DESCRIPTION
**Pull request by lumarogit**

### CODE REVIEW

**Comment by emmett1** [comment]
Does firefox required rust now?

One more thing, venom use 'pkgconf' now, not 'pkg-config'.

**Comment by emmett1** [comment]
Alright then. I will wait your fix then merge.

**Comment by lumarogit** [comment]
Pushed changes.

**Comment by emmett1** [comment]
Dont delete 'update' file. Its file for checking updates from upstream.

**Comment by lumarogit** [comment]
Oh ! I restored it.

**Pull request merged**
