### PR TITLE
Created ports for hyfetch and gdb

### PR DESCRIPTION
**Pull request by FragCGI**
Since neofetch is no longer maintained, I created a port for hyfetch which is maintained.
It still uses the neofetch script after it is installed.
I carried over the patch for the Venom logo, however, I also put in a pull request to have hyfetch update with the new Venom logo as well as a venom_small that I created.

I noticed that The GNU Project Debugger (gdb) was not included in the repos so I also created a port for that.

### CODE REVIEW

**Comment by lumarogit** [comment]
Hi, please update source name with "$name-$version ..." in hyfetch port. Alright, i will accept this PR, but for nexts Pull Request, each new port in one PR independt, thanks.

**Comment by FragCGI** [comment]
I will and thank you.

**Comment by lumarogit** [comment]
Please, check hyfetch port again and change "$name-$version.tar.gz .." and set release to version 1, thanks.

**Comment by FragCGI** [comment]
I fixed the source and version on my end, do I need to create a new pull request?
Sorry if that seems like a dumb question. I'm pretty new to all this git stuff.

**Pull request merged**
