### PR TITLE
New Ports

### PR DESCRIPTION
**Pull request by XDream8**
- gitui
- lf
- ps_mem
- shfmt
- sx
- symbola
- xwallpaper

### CODE REVIEW

**Comment by emmett1** [comment]
Can you fix the source? Make sure fetched source is uniq. You can use 'source="$name-$version.tar.gz::<source url>". For github you can use '..../archive/<the version from github>/$name-$version.tar.gz'

**Comment by XDream8** [comment]
Thanks! I didn't know that i could do that.

**Comment by XDream8** [comment]
Fixed now

**Comment by emmett1** [comment]
Nice thanks😁

**Pull request merged**
