### PR TITLE
Update mold 1.3.0

### PR DESCRIPTION
**Pull request by lumarogit**

### CODE REVIEW

**Comment by emmett1** [comment]
Dont remove 'libexec' sed. I intentionally add that. Venom does not use '/usr/libexec'.

**Comment by lumarogit** [comment]
Oh nice! I understand, fixed. Thanks !

**Comment by emmett1** [comment]
One more thing, please remove 'git' from depends. No ports depends on 'git' except scratchpkg (used for sync ports).

**Comment by lumarogit** [comment]
Removed git depend, fixed!

**Pull request merged**
