### PR TITLE
added btop pkg 1.2.13

### PR DESCRIPTION
**Pull request by umop3plsdn**
Added port for btop

### CODE REVIEW

**Comment by lumarogit** [comment]
Hi, please push this changes:

1) the source will saved as 'name-version.tar.gz' instead of 'vversion.tar.gz'. Edit sources:
source="$name-$version.tar.gz::https://github.com/aristocratos/${name}/archive/v${version}.tar.gz"

2) If "depends" is empty in spkgbuild, you can remove it.

3) Add PREFIX in make install to fix "/usr/local":
        make PREFIX=/usr
	make DESTDIR=$PKG PREFIX=/usr install

**Comment by umop3plsdn** [comment]
Thank you so much for the feedback! i'll make the changes

**Comment by umop3plsdn** [comment]
Is that better?

**Comment by lumarogit** [comment]
Hi, please edit source again and add "tar.gz" to "$name-$version":

source="$name-$version.tar.gz::[https://github.com/aristocratos/${name}/archive/v${version}.tar.gz](https://github.com/aristocratos/$%7Bname%7D/archive/v$%7Bversion%7D.tar.gz)"

Update the .checksums file with "pkgbuild -g"

Rebuild the package and update .pkgfiles with "pkgbuild -p"

Thanks.

**Comment by umop3plsdn** [comment]
done and done lol

**Pull request merged**
