### PR TITLE
neovim 0.8. dependencies pynvim and python3-msgpack

### PR DESCRIPTION
**Pull request by Spacefreak18**
neovim and it's dependencies.

I chose the option to compile with the bundled dependencies since it seemed easier than building a ton of ports.

### CODE REVIEW

**Comment by lumarogit** [comment]
Please fix neovim url, make sure source saved as '$name-$version.tar.gz'.

Upgrade to python 3.10 to build it, python 3.10.6 is the  stable version in Venom Linux.

Better one PR for each package.

Thanks !

**Comment by Spacefreak18** [comment]
I can't change the url, that's what it is and that's how it saves.

**Comment by lumarogit** [comment]
Try this:
source="$name-$version.tar.gz::https://github.com/$name/$name/archive/v$version.tar.gz"

**Comment by Spacefreak18** [comment]
that's pretty, i didn't know you could do that, thanks.

**Comment by lumarogit** [comment]
Please, check again:
$name-$version.tar.gz::https://github.com/$name/$name/archive/v$version.tar.gz"

It's '$version', not 'version'.

**Pull request merged**
