### PR TITLE
Added 5 ports

### PR DESCRIPTION
**Pull request by Byl3x**
The sdhcp port source is hosted on a temporary place, if that's a problem reupload it somewhere. I don't know how to use a git repository as the source(if it's possible).

### CODE REVIEW

**Comment by emmett1** [comment]
Its ok if its on temporary place as long its there as long as possible before i got a way to overcome it. 
Thanks for the PR of your ports but i saw you use `/usr/local`. For distro with package manager `/usr/local` is forbidden, i believe its on all linux distro exist. Same with Venom, use `--prefix=/usr` if possible. So i really cant merge it until you fix it.
For tlp port its looking good, extra tips; you can remove `/lib/elogind`. And Venom did not use `/etc/init.d` for initscript, you can convert it to BSD-like init compatible and placed it in `/etc/rc.d`.

**Comment by Byl3x** [comment]
I think I fixed everything(except the /etc/init.d but I added a runit service)

**Comment by emmett1** [comment]
Did you regenerate .pkgfiles after fix that because i still saw `/usr/local` in .pkgfiles. One more thing, ports cant use upper case. Maybe i will block on new scratchpkg.

**Comment by Byl3x** [comment]
Forgot to regenerate the .pkgfiles, regenerated them and also fixed the name

**Pull request merged**
