### PR TITLE
New port: sfeed-1.5-1

### PR DESCRIPTION
**Pull request by Visone-Selektah**
New Port: sfeed-1.5-1
RSS and Atom parser

### CODE REVIEW

**Comment by emmett1** [comment]
Man page directory in venom is '/usr/share/man/', please fix it first.

**Comment by emmett1** [comment]
Still not fix it. You put it at the same directory.

**Comment by Visone-Selektah** [comment]
Sorry! 
I missed */share but..
All *.1 have to be installed in /usr/share/man/man1/  and all  *.5 in /usr/share/man/man5/ , right?

**Comment by emmett1** [comment]
Yes correct.

**Pull request merged**
