### PR TITLE
acpid : add runit service file

### PR DESCRIPTION
**Pull request by Visone-Selektah**

### CODE REVIEW

**Comment by emmett1** [comment]
You forgot important symlink for runit service. See 'slim' runit service how i do it

**Comment by Visone-Selektah** [comment]
The symlink is only needed when you want to enable the service at install

**Comment by emmett1** [comment]
'ln -s /run/runit/supervise.$name $PKG/etc/sv/$name/supervise'

This symlink required to point supervise file created when service enabled to /run/runit directory. When runit service disabled, supervise file not removed, so this polluted the system, thats why point to /run/runit is required, so it will removed on reboot. Just like Void Linux did.

**Comment by Visone-Selektah** [comment]
Ok I'll check them 

Ok ok, I get it now!!!

**Pull request merged**
