### PR TITLE
Update xcb-proto-32 to 1.15.2

### PR DESCRIPTION
**Pull request by lumarogit**

### CODE REVIEW

**Comment by emmett1** [comment]
Why you change DESTDIR install command?? Its already correct. -32 packages only provides lib32 libraries.

**Comment by emmett1** [comment]
This has nothing to do with fail build. This command install files into temporary dir because -32 bit package only need /usr/lib32 directory, other files not needed. Try build again with initial DESTDIR command. If failed, give the error.

**Comment by emmett1** [comment]
Your changes make it install all files into package, this will caused conflict with its 64bit package.

**Comment by lumarogit** [comment]
+ make DESTDIR=/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR install
Making install in src
make[1]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
make[2]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/xcb'
 /usr/bin/install -c -m 644 xcb.xsd xproto.xml bigreq.xml composite.xml damage.xml dbe.xml dpms.xml dri2.xml dri3.xml ge.xml glx.xml present.xml randr.xml record.xml render.xml res.xml screensaver.xml shape.xml shm.xml sync.xml xc_misc.xml xevie.xml xf86dri.xml xf86vidmode.xml xfixes.xml xinerama.xml xinput.xml xkb.xml xprint.xml xselinux.xml xtest.xml xv.xml xvmc.xml '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/xcb'
make[2]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
Making install in xcbgen
make[1]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[2]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/lib/python3.9/site-packages/xcbgen'
 /usr/bin/install -c -m 644 __init__.py error.py expr.py align.py matcher.py state.py xtypes.py '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/lib/python3.9/site-packages/xcbgen'
Byte-compiling python modules...
__init__.pyerror.pyexpr.pyalign.pymatcher.pystate.pyxtypes.py
Byte-compiling python modules (optimized versions) ...
__init__.pyerror.pyexpr.pyalign.pymatcher.pystate.pyxtypes.py
Byte-compiling python modules (optimized versions) ...
__init__.pyerror.pyexpr.pyalign.pymatcher.pystate.pyxtypes.py
make[2]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[1]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
make[2]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/pkgconfig'
 /usr/bin/install -c -m 644 xcb-proto.pc '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/pkgconfig'
make[2]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
+ mkdir -p /var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32
+ cp -Rv DESTDIR/usr/lib32/* /var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32
cp: cannot stat 'DESTDIR/usr/lib32/*': No such file or directory
==> ERROR: Build failed: xcb-proto-32-1.15.2-1

**Comment by lumarogit** [comment]
> Your changes make it install all files into package, this will caused conflict with its 64bit package.

Oh ! I understand now, thanks.

**Comment by emmett1** [comment]
Add 'make' before make DESTDIR command

**Comment by lumarogit** [comment]
> Add 'make' before make DESTDIR command

Same error.

make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
+ make DESTDIR=/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR install
Making install in src
make[1]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
make[2]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/xcb'
 /usr/bin/install -c -m 644 xcb.xsd xproto.xml bigreq.xml composite.xml damage.xml dbe.xml dpms.xml dri2.xml dri3.xml ge.xml glx.xml present.xml randr.xml record.xml render.xml res.xml screensaver.xml shape.xml shm.xml sync.xml xc_misc.xml xevie.xml xf86dri.xml xf86vidmode.xml xfixes.xml xinerama.xml xinput.xml xkb.xml xprint.xml xselinux.xml xtest.xml xv.xml xvmc.xml '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/xcb'
make[2]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/src'
Making install in xcbgen
make[1]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[2]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/lib/python3.9/site-packages/xcbgen'
 /usr/bin/install -c -m 644 __init__.py error.py expr.py align.py matcher.py state.py xtypes.py '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/lib/python3.9/site-packages/xcbgen'
Byte-compiling python modules...
__init__.pyerror.pyexpr.pyalign.pymatcher.pystate.pyxtypes.py
Byte-compiling python modules (optimized versions) ...
__init__.pyerror.pyexpr.pyalign.pymatcher.pystate.pyxtypes.py
Byte-compiling python modules (optimized versions) ...
__init__.pyerror.pyexpr.pyalign.pymatcher.pystate.pyxtypes.py
make[2]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/xcbgen'
make[1]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
make[2]: Entering directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/pkgconfig'
 /usr/bin/install -c -m 644 xcb-proto.pc '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2/DESTDIR/usr/share/pkgconfig'
make[2]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
make[1]: Leaving directory '/var/cache/scratchpkg/work/xcb-proto-32/src/xcb-proto-1.15.2'
+ mkdir -p /var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32
+ cp -Rv DESTDIR/usr/lib32/* /var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32
cp: cannot stat 'DESTDIR/usr/lib32/*': No such file or directory
==> ERROR: Build failed: xcb-proto-32-1.15.2-1

**Comment by emmett1** [comment]
Ok found why. New version changed datadir. Use this patch to revert that;

https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/commit/d849b9534a52b0199f26c1dd30ac11aba12db9dc.patch

**Comment by lumarogit** [comment]
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.am.rej
==> ERROR: Build failed: xcb-proto-32-1.15.2-1

**Comment by emmett1** [comment]
forget the patch.

add this before configure:

`sed 's/datarootdir/libdir/' -i Makefile.am`
`autoreconf -fi`

**Comment by lumarogit** [comment]
Nice !!! 

+ cp -Rv DESTDIR/usr/lib32/pkgconfig /var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32
'DESTDIR/usr/lib32/pkgconfig' -> '/var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32/pkgconfig'
'DESTDIR/usr/lib32/pkgconfig/xcb-proto.pc' -> '/var/cache/scratchpkg/work/xcb-proto-32/pkg/usr/lib32/pkgconfig/xcb-proto.pc'
==> Build success: xcb-proto-32-1.15.2-1
drwxr-xr-x root/root         0 2022-07-04 12:39 usr/
drwxr-xr-x root/root         0 2022-07-04 12:39 usr/lib32/
drwxr-xr-x root/root         0 2022-07-04 12:39 usr/lib32/pkgconfig/
-rw-r--r-- root/root       303 2022-07-04 12:39 usr/lib32/pkgconfig/xcb-proto.pc
==> Packaging success: xcb-proto-32-1.15.2-1.spkg.tar.xz (404)
==> Pkgfiles updated.

**Comment by emmett1** [comment]
👍

**Pull request merged**
