### PR TITLE
Fix for "main/atril building fails #3149"

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AldairbotHerotaku** [comment]
That should fix it but it failed anyways lol

**Comment by lumarogit** [comment]
Hi, I checked it and atril build fine for me  with new deps, what it's the error? You can enter the telegram group to get faster feedback.

https://t.me/venomlinux

**Comment by emmett1** [comment]
Why added python2 build? Python2 already removed from venom.

**Comment by Visone-Selektah** [comment]
This PR was resolved as issue, it can be close

**Pull request closed without merging**
