### PR TITLE
Personal repo keepassxc building

### PR DESCRIPTION
**Pull request by daemonbsd56**
keepassxc built wiht these new packages argon2 libsodium qrencode

### CODE REVIEW

**Comment by daemonbsd56** [comment]
Updating Frameworks-5.57 and plasma5-5.15.4

**Comment by daemonbsd56** [comment]
kf5 fully updated to latest april 2019 stable version.

**Comment by daemonbsd56** [comment]
Reopened pull request with the kf5 updates. Testing github management

**Comment by emmett1** [comment]
I've updated kf5 ports :D

**Pull request closed without merging**
