### PR TITLE
Fix checksums

### PR DESCRIPTION
**Pull request by Visone-Selektah**

### CODE REVIEW

**Comment by emmett1** [comment]
Why you change removing completion part? The old one is better, simpler

**Comment by Visone-Selektah** [comment]
I change it cause it breaks that way. Doesn't get anything after `&&` in any of those two lines

**Comment by emmett1** [comment]
I think you need 'rm -rf $PKG/...'. Mind the 'f' for force remove even it does not exist in $PKG, this will return 0.

**Comment by Visone-Selektah** [comment]
Even adding force still breaking

**Comment by emmett1** [comment]
Whattt? This is very forbidden!. Never do this in ports. What you trying to do is removing files in real system while building a package. I will reject this immedietely without thinking twice.

**Pull request merged**
