### PR TITLE
GUI configuration tool for compton

### PR DESCRIPTION
**Pull request by SACViper**
compton-conf is a GUI tool for compton configuration

### CODE REVIEW

**Comment by emmett1** [comment]
I saw compton-conf binary and its stuff got installed in /usr/local. Package never install files in /*/local directory.

**Comment by SACViper** [comment]
it can be install /opt directory  as its just addon to compton whats your suggestion ? :)

**Comment by emmett1** [comment]
Its compiled from source, so it should in /usr
Example, for binary in /usr/bin/ data files in /usr/share
You need to fix build cmd.

**Comment by SACViper** [comment]
Sorry, I just did that thank you @emmett1 , I am learning more from your guidence cheers

**Comment by emmett1** [comment]
Its ok, i happy teaching other people in linux. I’m also still learning. :)

**Pull request merged**
